[top]
# model_choice.txt
# This file is for making model choices for a single run of McFACTS
# It is your start up file (or template)! 
# See IOdocumentation.txt for details.
#
# SMBH mass in units of M_sun:
smbh_mass = 1.e8
#
# SMBH accretion disk:
#
# Specify prefix to filenames for input disk model
disk_model_name = 'sirko_goodman'
# pAGN flag (0/1) boolean
flag_use_pagn = 1
# surrogate model flag (0/1) boolean
flag_use_surrogate = 0
# spin filter check flag (0/1)
flag_use_spin_check = 0

# trap radius in r_g
disk_radius_trap = 700.
# disk outer radius in r_g
disk_radius_outer = 50000.
# Maximum disk outer radius (pc) (0. turns this off)
disk_radius_max_pc = 0.
# disk alpha parameter (viscosity parameter, alpha=0.01 in sirko_goodman)
disk_alpha_viscosity = 0.01
# Outer radius of the inner disk (Rg)
inner_disk_outer_radius = 50.
# Innermost Stable Circular Orbit around the SMBH (Rg)
disk_inner_stable_circ_orb = 6.
# Torque prescription ('old','paardekooper','jimenez_masset': Paaardekooper default; Jimenez-Masset option)
torque_prescription = 'paardekooper'
#phenomenological turbulence
flag_phenom_turb = 0
#Centroid of Gaussian w.r.t. to migrating BH. 0 (default)
phenom_turb_centroid = 0.
#Variance of Gaussian around Centroid (default=0.1)
phenom_turb_std_dev = 0.1


#
# Nuclear Star Cluster Population:
#
#Outer radius of NSC (1-10pc) in units of pc
nsc_radius_outer = 5.0
#Mass of NSC in M_sun. Milky Way NSC is 3x10^7Msun. Typically 10^6-8Msun from obs
nsc_mass = 3.e7
#Inner critial NSC radius (where radial number density changes) in units of pc. 0.25pc for SgrA* (Generozov+18).
nsc_radius_crit = 0.25
#Ratio of number of BH to number of Stars (spans 3x10^-4 to 10^-2 in Generozov+18)
nsc_ratio_bh_num_star_num = 1.e-3
#Typical ratio of mass of BH to mass of star (10Msun:1Msun in Generozov+18)
nsc_ratio_bh_mass_star_mass = 10.0
#Radial density index for inner NSC, for r<r_nsc_crit. n propto r^-7/4 for Bahcall-Wolf (& Generozov+18)
nsc_density_index_inner = 1.75
#Radial density index for outer NSC, for r>r_nsc_crit. n propto r^-2.5 for Generozov+18, r^-2.25 Peebles
nsc_density_index_outer = 2.5
#Average aspect ratio of disk (calculate this based on r_disk_outer?). Roughly 3% or so for Sirko&Goodman03.
disk_aspect_ratio_avg = 0.03
#Normalize spheroid component rate of interactions (default = 1.0)
nsc_spheroid_normalization = 1.0

# Mode of initial BH mass distribution in M_sun (peak of Pareto fn)
nsc_imf_bh_mode = 10.
# Pareto (powerlaw) initial BH mass index
nsc_imf_bh_powerlaw_index = 2.
# Maximum initial BH mass in distribution in M_sun
nsc_imf_bh_mass_max = 40.
# NSC BH imf method
nsc_imf_bh_method = 'default'
# Mean of Gaussian initial spin distribution 
nsc_bh_spin_dist_mu = 0.
# Sigma of Gaussian initial spin distribution 
nsc_bh_spin_dist_sigma = 0.1
# Spin torque condition
disk_bh_torque_condition = 0.1
# Accretion rate of fully embedded stellar mass black hole in units of 
#   Eddington accretion rate
disk_bh_eddington_ratio = 1.0
# Maximum initial eccentricity
disk_bh_orb_ecc_max_init = 0.9
# Mass pile-up term
mass_pile_up = 35.
#
#
#Star stuff
flag_add_stars = 1
# If 1: stars over disk_star_initial_mass_cutoff turn into BH. If 0: stars over disk_star_initial_mass_cutoff are held at the cutoff and are immortal. Default 0.
flag_initial_stars_BH_immortal = 0
# If 0: star masses are drawn from IMF and not changed before beginning of time loop. If 1: stars within each others Hill spheres are merged together before the beginning of the time loop.
flag_coalesce_initial_stars = 0
# Maximum initial star mass before flag_initial_stars_BH_immortal behavior kicks in. Default 300.
disk_star_initial_mass_cutoff = 298.
# Factor by which to scale the number of stars in the disk at the beginning of the galaxy. Default 0.5e-2.
disk_star_scale_factor = 0.5e-2
disk_star_mass_min_init = 0.5
disk_star_mass_max_init = 10.
nsc_imf_star_powerlaw_index = 2.35
nsc_imf_star_mass_mode = 2.0
disk_star_torque_condition = 0.1
disk_star_eddington_ratio = 1.0
disk_star_orb_ecc_max_init = 0.3
#These values are from Yusof+2022 (2022MNRAS.511.2814Y)
nsc_star_metallicity_x_init = 0.7064
nsc_star_metallicity_y_init = 0.2735
nsc_star_metallicity_z_init = 0.02

# Timing:
# 
# timestep in years (float)
timestep_duration_yr = 1.e4
# For timestep=1.e4, number_of_timesteps=100 gives us 1Myr disk lifetime
timestep_num = 70

# number of galaxies of code (1 for testing. 30 for a quick run.)
galaxy_num = 1
#
# Other physics choices: 
#
# New retrograde binary switch
fraction_bin_retro = 0.0
# feedback on/off switch. Feedback = 1(0) means feedback is allowed(off)
flag_thermal_feedback = 1
# eccentricity damping (1/0) switch. 
# orb_ecc_damping = 1 means orbital damping is on & orb ecc is drawn from e.g. uniform or thermal distribution
# orb_ecc_damping = 0 means orbital damping is off and all BH are assumed to be on circularized orbits (=e_crit)
flag_orb_ecc_damping = 1
# Disk capture 
# capture time in years (float). Secunda et al. (2021) assume capture rate 1/0.1Myr
capture_time_yr = 1.e5
# Disk capture outer radius (in units of r_g). Secunda et al. (2021) assume <2000r_g from Fabj et al. (2020)
disk_radius_capture_outer = 1.e3
#Critical eccentricity (limiting eccentricity, below which assumed circular orbit)
disk_bh_pro_orb_ecc_crit = 0.01
#Dynamics on/off switch. Dynamics = 0(1) means dynamical encounters are off (on)
flag_dynamic_enc = 1
# Mean of Delta Energy per Strong interaction (can be up to 20%,0.2)
delta_energy_strong_mu = 0.1
# Sigma of delta energy per strong interaction
delta_energy_strong_sigma = 0.02
# Average energy exchanged in a strong 2 + 1 interaction that hardens the binary
harden_energy_delta_mu = 0.9
# Variance of the energy exchanged in a strong 2 + 1 interaction that hardens the binary
harden_energy_delta_sigma = 0.025
# Computational
flag_dynamics_sweep = 1
